package models

import "gorm.io/gorm"

type Doctor struct {
	gorm.Model
	//want to omitempty all autogenerated fields like Created_At, Updated_At, ID
	Name         string        `json:"name"`
	Schedule     []Appointment `gorm:"foreignKey:d_id" json:"schedule,omitempty"`
	Email        string        `gorm:"unique" json:"email"`
	Password     string        `json:"password,omitempty"`
	Availability []string      `gorm:"type:text" json:"availability,omitempty"`
	Role         string        `json:"role,omitempty"`
}
