package models

import "gorm.io/gorm"

type Patient struct {
	gorm.Model
	//want to omitempty all autogenerated fields like Created_At, Updated_At, ID
	Name     string        `json:"name"`
	Email    string        `gorm:"unique" json:"email"`
	Password string        `json:"password,omitempty"`
	Role     string        `json:"role,omitempty"`
	History  []Appointment `gorm:"foreignKey:p_id" json:"history,omitempty"`
}
